server:
  port: 8861

spring:
  application:
    name: device-service
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3307/device_service?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
      server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 1
        prefetch: 1
nacos:
  discovery:
    auto-registration: true

seata:
  enabled: true
  application-id: device-service
  enable-auto-data-source-proxy: false

