server:
  port: 8853

spring:
  application:
    name: ticket-service
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3307/ticket_service?useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
      server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848

nacos:
  discovery:
    auto-registration: true

seata:
  enabled: true
  application-id: ticket-service
  enable-auto-data-source-proxy: false
